openapi: 3.0.3
info:
  title: Milieu zone koppel api
  description: Milieu zone koppel api
  version: 1.0.0
paths:
  /milieu/get:
    parameters:
      - name: Authorization
        in: header
        description: Bearer token
        required: true
        schema:
          type: string
    get:
      summary: Meldingen en tips uit het milieuzone portaal op basis van BSN.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    nullable: true
                    $ref: "#/components/schemas/UserInfo"
                  status:
                    type: string
                    enum:
                      - "OK"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /status/health:
    get:
      summary: returns "OK"
      responses:
        "200":
          description: Returns "OK"
          content:
            application/json:
              schema:
                type: string
                enum:
                  - "OK"
components:
  schemas:
    UserInfo:
      type: object
      properties:
        isKnown:
          type: boolean
        notifications:
          type: array
          items:
            $ref: "#/components/schemas/MyNotification"
        tips:
          type: array
          items:
            $ref: "#/components/schemas/Tip"
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - "ERROR"
        message:
          type: string
    MyNotification:
      type: object
      properties:
        datePublished:
          type: string
          format: date
          example: '2019-12-13'
        description:
          type: string
          example: 'Uw aanvraag voor ontheffing milieuzone Brom/Snor is afgewezen'
        id:
          type: string
          example: 'milieu-F3'
        priority:
          type: number
          example: 0
        title:
          type: string
          example: 'Uw aanvraag ontheffing milieuzone Brom/Snor'
        link:
          $ref: '#/components/schemas/Link'
    Tip:
      type: object
      properties:
        datePublished:
          type: string
          format: date-time
          example: '2020-01-28T13:11:51Z'
        description:
          type: string
          example: 'Er staat nog een aanslag open van u. Zorg voor tijdige betaling.'
        id:
          type: string
          example: 'belasting-4'
        priority:
          type: number
          example: 1
        title:
          type: string
          example: 'Betaal uw aanslagen'
        link:
          $ref: '#/components/schemas/Link'
        reason:
          type: string
          example: 'U krijgt deze tip omdat u nog niet via automatische incasso betaalt'
    Link:
      type: object
      properties:
        title:
          type: string
          example: 'Meer informatie'
        to:
          type: string
          example: 'https://ontheffingen-acc.amsterdam.nl/publiek/aanvraag/5A158FD9-B07D-4A4C-B780-8359A9A14906'
